version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install cfn-lint

  pre_build:
    commands:
      - cfn-lint cloudformation/main-stack.yaml

  build:
    commands:
      - echo "Packaging CloudFormation templates..."
      - aws cloudformation package --template-file cloudformation/main-stack.yaml --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged-template.yaml

artifacts:
  base-directory: .
  files:
    - packaged-template.yaml
    - cloudformation/parameters.json
